### ISSUE TITLE
Why not using the jspm bower repository ?

### ISSUE THREAD

**Issue by Yvem** [Munter/bower-to-jspm#1]
``` bash
npm install --save jspm-bower-endpoint
jspm registry create bower jspm-bower-endpoint -y
jspm install bower:d3
...
```

a particular reason ? I'm interested...

**Comment by Munter** [comment]
This didn't exists at the time I write this. Or at least noone could get it to work.

@guybedford would you say the jspm-bower-endpoint is stable and can replace the need for a tedious conversion to jspm endpoints if you are trying to switch a bower setup to jspm? If so I'll just put a deprecation notice on this package with the above instructions. It was a hack anyway

**Comment by guybedford** [comment]
The jspm-bower-endpoint is a third-party project, which I would actually discourage using myself, as it duplicates a lot of what is already in the github registry.
